## Github action to run:
# 1. Install dependencies
# 2. Build the project
# 3. Run tests (if any)
# 4. Check if the version was bumped, if there are changes in the dist folder.

name: Build, Test & Verify dist
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build
          npm run lint

      - name: Run tests
        run: npm run test

      - name: Check version bump # If there are changes in 'dist', was the package version bumped?
        run: |
          git fetch origin main

          git diff --exit-code --name-only dist/

          if [ $? -ne 0 ]; then
            echo "New files generated in /dist folder. Please commit the changes."
            exit 1
          fi

          package_version=$(jq -r .version package.json)
          origin_package_version=$(git show origin/main:package.json | jq -r .version)
          if [ "$(git diff origin/main --name-only dist/ | wc -l)" -gt "0" ]; then
            if [ "$package_version" == "$origin_package_version" ]; then
              echo "Version not bumped, but dist/ changed. Please bump the version in package.json."
              exit 1
            fi
          fi
